name: Build and Publish Chatbot UI
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: caomingjun/chatbotui

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'mckaywrigley/chatbot-ui'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: caomingjun
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.time.outputs.time }},${{ env.IMAGE_NAME }}:latest
